import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopHeader from "./components/TopHeader";
import Header from "./components/Header";
import MobNav from "./components/MobNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <body className={inter.className}>
      <TopHeader />

       <div className="hidden lg:block">
        <Header />
    </div>

    <div className="lg:hidden">
    <MobNav />
    </div>
        {children}
        
        </body>
    </html>
  );
}
